import { chromium } from "@playwright/test";
const base = "http://localhost:3410";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(`${base}/sign-in`);
await page.getByLabel("Email").fill("dana@demo.invalid");
await page.getByLabel("Password").fill("password");
await page.getByRole("button", { name: /sign in/i }).click();
await page.waitForURL(/\/shop/, { timeout: 60000 });
await page.goto(`${base}/shop/blue-mantis/settings/security`, { waitUntil: "networkidle" });
console.log(await page.locator("main").innerText());
await browser.close();
