allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  msw: true

minimumReleaseAge: 0

patchedDependencies:
  '@vercel/analytics@2.0.1': patches/@vercel__analytics@2.0.1.patch

publicHoistPattern:
  - '@img/*'
  - 'detect-libc'
  - 'semver'

update:
  ignoreDeps:
    - '@types/node'
