allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  msw: true

minimumReleaseAge: 0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - msw

publicHoistPattern:
  - '@img/*'
  - 'detect-libc'
  - 'semver'

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
