-- DATA-L4 (review 20260802), the contract half. `20260806051740_course-gallery-photos`
-- added `gallery_photos` — one `{ url, alt }` object per photo — backfilled it from the
-- positionally-correlated `image_urls` / `image_alts` pair, and dropped nothing. Nothing has
-- *read* the two old columns by name since that release; this one deletes the dual-write
-- (`legacyGalleryColumns`, src/db/courses.ts) and removes them.
--
-- Both halves land in one release, and that is a deliberate departure from the runbook, not an
-- oversight. The four-step rename table in docs/engineering/deploy-and-migrations-runbook.md puts
-- "stops writing" and "drop" together in release 4; the caveat directly under it says the drop must
-- land only after every running instance has stopped touching the column, "including the deployment
-- that was live thirty seconds ago". Those two are in tension, and migrations apply inside the
-- production build while the previous release is still serving, so this release resolves the
-- tension by accepting the cost rather than by splitting into two deploys.
--
-- What that costs, measured rather than assumed. Drizzle's `db.select().from(courses)` compiles to
-- an explicit column list, not `SELECT *`, so the previous release names `image_urls` and
-- `image_alts` in its *reads* as well as its writes. For the length of the deploy, every one of
-- these fails on the previous release with `column courses.image_urls does not exist`:
--
--   * the public course catalog and course page (`listActiveCourses`, `getCourseBySlug`);
--   * the staff course roster and editor (`listCourses`, `pagedCourses`, `getCourseBySlug`);
--   * booking or claiming a seat on a course session, and creating a course departure
--     (`bookSpot` and `createBookingRecord` in src/db/bookings.ts, src/db/seat-claims.ts,
--     src/db/trips-create.ts — each loads the course row whenever a trip has a `course_id`);
--   * the CSV export bundle and the weekly backup export (`loadShopExportBundleInput`).
--
-- Surfaces that never touch `courses` are unaffected, as is anything selecting named columns
-- (`hasActiveCourses`, the ⌘K search arm) — but the diver-facing course funnel is not a
-- write-only path, and this window is larger than "a course edit fails".
--
-- Second accepted cost: Instant Rollback to the previous release stops being safe the moment this
-- applies, because that deployment would then be permanently broken in the ways above rather than
-- briefly. Rolling back past this release means a forward migration or branching Neon from a
-- timestamp (the runbook's "Rollback" section), not the dashboard button.
--
-- Both costs were put to the owner and accepted in preference to splitting this across two deploys.
-- The two acknowledgement lines below are that decision on the record, one per statement.
-- diveday:allow-destructive drop-column courses.image_urls: unread since 20260806051740 and the dual-write is deleted in this same release; the previous release's reads and writes of it failing for the length of the deploy, and the loss of Instant Rollback past this release, were accepted deliberately
ALTER TABLE "courses" DROP COLUMN "image_urls";--> statement-breakpoint
-- diveday:allow-destructive drop-column courses.image_alts: same call as image_urls above — unread since 20260806051740, dual-write deleted here, and the deploy-window breakage on the previous release plus the loss of Instant Rollback past this release were accepted deliberately
ALTER TABLE "courses" DROP COLUMN "image_alts";
