-- Merge migration: reconciles two independently-generated migration heads
-- (20260801035541_person-courtesy-email-unsubscribe and
-- 20260801042741_checkout-booking-gear-cents) that both trace back to the
-- same 20260731231802_shop-currency-and-person-locale /
-- 20260801001928_last-minute-list-unsubscribe-tokens fork without either
-- declaring the other as a parent -- the same class of fork the
-- 20260801010000_merge-currency-locale-and-unsubscribe-tokens migration
-- already resolved once, recurring because a sibling branch (checkout-
-- booking-gear-cents) merged the same two original heads independently
-- rather than building on top of that resolution. Both sides here are
-- purely additive and touch disjoint objects (the courtesy-email
-- unsubscribe token table/column vs booking_checkout_bookings.gear_cents),
-- so there is nothing left to apply here -- this migration exists only to
-- give drizzle-kit generate a single unambiguous tip to diff future schema
-- changes against.
