#!/usr/bin/env node
// Writes the index table in docs/architecture/decisions/README.md: one row per ADR — id, title,
// status, superseded-by — sorted by id. `scripts/check-adrs.mjs` fails when the committed table
// differs from what this would write, so the index cannot drift from the files.
//
//   node scripts/adr-index.mjs --write
//
// The table sits between two marker comments and nothing else in the README is touched. Two
// branches that each add an ADR each add one row; when the rows land next to each other git
// reports a conflict in the table, and the resolution is to take either side and run this
// again, never to merge the rows by hand.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

export const DECISIONS_DIR = "docs/architecture/decisions";
export const START = "<!-- adr-index:start (generated by node scripts/adr-index.mjs --write) -->";
export const END = "<!-- adr-index:end -->";

/** Every ADR file name in the directory, sorted: everything but the README and the template. */
export function adrFiles(dir) {
  return readdirSync(dir)
    .filter((name) => name.endsWith(".md") && name !== "README.md" && name !== "0000-template.md")
    .sort();
}

/**
 * `{ id, title, status, supersededBy }` from one ADR's text. The successor is the first id in
 * `known` that the status line names, linked or bare — status lines are prose ("Superseded on
 * 2026-09-20 by …"), so a date is never mistaken for an id.
 */
export function adrSummary(filename, contents, known = new Set()) {
  const id = filename.replace(/\.md$/, "");
  const title = contents.match(/^#\s+\S+\s+[—-]\s+(.+)$/m)?.[1]?.trim() ?? "";
  const statusLine = contents.match(/^- \*\*Status:\*\*\s+([^\n]+)$/m)?.[1]?.trim() ?? "";
  const status = statusLine.match(/^(Proposed|Accepted|Deprecated|Superseded)/)?.[1] ?? "";
  const supersededBy =
    status === "Superseded"
      ? ((statusLine.match(/\d{4}(?:\d{4})?-[a-z0-9-]+/g) ?? []).find((token) =>
          known.has(token),
        ) ?? "")
      : "";
  return { id, title, status, supersededBy };
}

const cell = (text) => text.replace(/\\/g, "\\\\").replace(/\|/g, "\\|");

/** The table, header included, one line per ADR. */
export function indexTable(summaries) {
  const rows = summaries.map(
    ({ id, title, status, supersededBy }) =>
      `| [${id}](${id}.md) | ${cell(title)} | ${status} | ${supersededBy ? `[${supersededBy}](${supersededBy}.md)` : ""} |`,
  );
  return ["| ADR | Decision | Status | Superseded by |", "| --- | --- | --- | --- |", ...rows].join(
    "\n",
  );
}

/** The README with its marked block replaced by `table`; null when the markers are missing. */
export function withIndex(readme, table) {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start === -1 || end === -1 || end < start) return null;
  return `${readme.slice(0, start + START.length)}\n\n${table}\n\n${readme.slice(end)}`;
}

/** What the README should be, read from the tree at `root`. */
export function expectedReadme(root) {
  const dir = path.join(root, DECISIONS_DIR);
  const files = adrFiles(dir);
  const known = new Set(files.map((name) => name.replace(/\.md$/, "")));
  const summaries = files.map((name) =>
    adrSummary(name, readFileSync(path.join(dir, name), "utf8"), known),
  );
  const readme = readFileSync(path.join(dir, "README.md"), "utf8");
  return { readme, expected: withIndex(readme, indexTable(summaries)) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
  const { readme, expected } = expectedReadme(root);
  if (expected === null) {
    console.error(`${DECISIONS_DIR}/README.md has no ${START} … ${END} block to fill.`);
    process.exit(1);
  }
  if (process.argv.includes("--write")) {
    if (expected !== readme) writeFileSync(path.join(root, DECISIONS_DIR, "README.md"), expected);
    console.log("adr-index: README.md index written");
  } else {
    console.log(expected === readme ? "adr-index: current" : "adr-index: stale (run with --write)");
  }
}
