import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  ageClaims,
  claimsTouching,
  classifyClaim,
  latestClaimIn,
  normalizeWorktree,
  parseClaim,
} from "./claims.mjs";

const ROOT = "/repo";
const NOW = new Date("2026-08-21T12:00:00Z");

const CLAIM = `> *This was generated by AI during triage.*

## Claim

**Branch:** claude/course-templates-a1b2c3
**Worktree:** .claude/worktrees/course-templates-a1b2c3
**Started:** 2026-08-21T09:00:00Z
**Owns:** \`src/db/course-templates.ts\`, \`public/marine-life/\`
**Also touches:** src/i18n/locales/en-US/staff/courses.json
`;

function facts({ worktrees = [], branches = {} } = {}) {
  return {
    root: ROOT,
    worktreePaths: new Set(worktrees.map((entry) => path.resolve(ROOT, entry))),
    branchLastCommit: new Map(Object.entries(branches).map(([name, iso]) => [name, new Date(iso)])),
  };
}

describe("parseClaim", () => {
  it("reads every field off a well-formed claim", () => {
    const claim = parseClaim(CLAIM);
    expect(claim).not.toBeNull();
    expect(claim.branch).toBe("claude/course-templates-a1b2c3");
    expect(claim.worktree).toBe(".claude/worktrees/course-templates-a1b2c3");
    expect(claim.startedAt.toISOString()).toBe("2026-08-21T09:00:00.000Z");
    expect(claim.owns).toEqual(["src/db/course-templates.ts", "public/marine-life/"]);
    expect(claim.alsoTouches).toEqual(["src/i18n/locales/en-US/staff/courses.json"]);
  });

  it("ignores a comment that is not a claim", () => {
    expect(parseClaim("## Agent Brief\n\n**Branch:** nope")).toBeNull();
  });

  // The whole point of a claim is that it can be disproved. One missing the branch or the
  // worktree cannot be checked against anything, so it is not treated as a claim at all.
  it.each(["Branch", "Worktree", "Started"])("refuses a claim with no %s", (missing) => {
    const stripped = CLAIM.split("\n")
      .filter((line) => !line.startsWith(`**${missing}:**`))
      .join("\n");
    expect(parseClaim(stripped)).toBeNull();
  });

  it("refuses a claim whose Started is not a date", () => {
    expect(parseClaim(CLAIM.replace("2026-08-21T09:00:00Z", "soon"))).toBeNull();
  });

  it("treats an unfilled placeholder as absent", () => {
    expect(parseClaim(CLAIM.replace("claude/course-templates-a1b2c3", "TBD"))).toBeNull();
  });

  it("survives smart quotes and missing bold markers", () => {
    const plain = CLAIM.replace(/\*\*/g, "").replace(/'/g, "’");
    expect(parseClaim(plain)?.branch).toBe("claude/course-templates-a1b2c3");
  });
});

describe("latestClaimIn", () => {
  it("takes the newest claim when a session re-claims", () => {
    const comments = [
      { body: CLAIM, createdAt: "2026-08-20T09:00:00Z" },
      { body: CLAIM.replace("a1b2c3", "d4e5f6"), createdAt: "2026-08-21T09:00:00Z" },
    ];
    expect(latestClaimIn(comments).branch).toBe("claude/course-templates-d4e5f6");
  });

  it("is null when no comment is a claim", () => {
    expect(latestClaimIn([{ body: "looks good to me", createdAt: NOW.toISOString() }])).toBeNull();
  });
});

describe("classifyClaim", () => {
  const claim = parseClaim(CLAIM);

  it("is live while the worktree is still on disk, even with no commits", () => {
    const verdict = classifyClaim(claim, facts({ worktrees: [claim.worktree] }), NOW);
    expect(verdict.state).toBe("live");
    expect(verdict.reason).toBe("worktree present");
  });

  it("is live when the branch advanced after the claim, even with the worktree gone", () => {
    const verdict = classifyClaim(
      claim,
      facts({ branches: { [claim.branch]: "2026-08-21T10:00:00Z" } }),
      NOW,
    );
    expect(verdict.state).toBe("live");
    expect(verdict.reason).toBe("branch advanced");
  });

  // The case the whole module exists for: a session that died leaving nothing behind.
  it("is stale when the worktree is gone and the branch never moved", () => {
    const verdict = classifyClaim(
      claim,
      facts({ branches: { [claim.branch]: "2026-08-20T09:00:00Z" } }),
      NOW,
    );
    expect(verdict.state).toBe("stale");
    expect(verdict.reason).toBe("worktree gone, branch has no commit since the claim");
  });

  it("is stale, and says so differently, when the branch does not exist at all", () => {
    const verdict = classifyClaim(claim, facts(), NOW);
    expect(verdict.state).toBe("stale");
    expect(verdict.reason).toBe("worktree gone, branch does not exist");
  });

  // Never guess a verdict that could not be checked — that is the registry problem again.
  it("is unverifiable rather than stale when git could not be read", () => {
    expect(classifyClaim(claim, null, NOW).state).toBe("unverifiable");
  });

  it("ages from the claim's own timestamp", () => {
    expect(classifyClaim(claim, facts(), new Date("2026-08-24T09:00:00Z")).days).toBe(3);
  });
});

describe("normalizeWorktree", () => {
  it("resolves a repo-relative path against the root", () => {
    expect(normalizeWorktree(".claude/worktrees/foo", ROOT)).toBe("/repo/.claude/worktrees/foo");
  });

  it("keeps an absolute path, since worktrees legitimately live outside the repo", () => {
    expect(normalizeWorktree("/elsewhere/foo", ROOT)).toBe("/elsewhere/foo");
  });

  it("tolerates a trailing slash so two spellings of one worktree match", () => {
    expect(normalizeWorktree(".claude/worktrees/foo/", ROOT)).toBe(
      normalizeWorktree(".claude/worktrees/foo", ROOT),
    );
  });

  // A traversal reaches nothing because this only ever produces a string to compare against
  // git's own output — there is no filesystem call and no subprocess for it to escape into.
  it("resolves a traversal to a path that simply matches nothing", () => {
    expect(normalizeWorktree("../../etc", ROOT)).toBe("/etc");
  });
});

describe("ageClaims", () => {
  const issue = (number, body) => ({
    number,
    title: `Issue ${number}`,
    comments: body ? [{ body, createdAt: "2026-08-21T09:00:00Z" }] : [],
  });

  it("reports a labelled issue carrying no claim comment", () => {
    const [entry] = ageClaims([issue(1, null)], facts(), NOW);
    expect(entry.verdict.state).toBe("unclaimed");
    expect(entry.claim).toBeNull();
  });

  it("sorts oldest claim first", () => {
    const older = CLAIM.replace("2026-08-21T09:00:00Z", "2026-08-01T09:00:00Z");
    const entries = ageClaims([issue(1, CLAIM), issue(2, older)], facts(), NOW);
    expect(entries.map((entry) => entry.id)).toEqual(["#2", "#1"]);
  });
});

describe("claimsTouching", () => {
  const entries = ageClaims(
    [{ number: 1, title: "t", comments: [{ body: CLAIM, createdAt: NOW.toISOString() }] }],
    facts(),
    NOW,
  );

  it("matches an exact owned file", () => {
    expect(claimsTouching(entries, ["src/db/course-templates.ts"])).toHaveLength(1);
  });

  it("matches a directory the claim owns beneath", () => {
    expect(claimsTouching(entries, ["public/marine-life/atlantic-blue-tang.jpg"])).toHaveLength(1);
  });

  it("matches a parent directory of an owned file", () => {
    expect(claimsTouching(entries, ["src/db"])).toHaveLength(1);
  });

  it("does not match a coincidental prefix", () => {
    expect(claimsTouching(entries, ["src/dbx"])).toHaveLength(0);
  });

  it("does not match an unrelated path", () => {
    expect(claimsTouching(entries, ["src/lib/today.ts"])).toHaveLength(0);
  });
});
