#!/usr/bin/env node
/**
 * Writes one target environment file from the two sources that own values.
 *
 * Two inputs, no merge:
 *
 *  - **stdin** — the `diveday/env` credentials document the CDK stack produced.
 *    Everything the stack mints or names, plus `APP_SECRET_SEED`, from which
 *    the three app secrets are derived here rather than stored anywhere.
 *  - **`.env.manual`** — the values no system can mint, typed by a human.
 *
 * Every key belongs to exactly one of them, decided in `config/env-registry.mjs`,
 * so there is nothing to arbitrate. That is the point. The previous version
 * merged the stack's document into whatever the target file already contained
 * and let the file win, which meant a credential typed into `.env.local` once
 * could never be refreshed — and, because `.env.vercel` was then rendered from
 * `.env.local` rather than from the secret, that stale value was carried into
 * production, where it read as a 403 from a service whose key was "right there
 * in the env" (ADR 20260812-env-provenance-registry).
 *
 * Targets are the *destinations*: `local` is the generated `.env.local` a dev
 * run reads, `vercel` the deployed environment, `github` the Actions secrets the
 * visual suite needs. Which keys reach which is `targets` in the registry.
 *
 * Usage: node scripts/distribute-env.mjs <local|vercel|github> <output> < document
 */
import { hkdfSync } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ENV_KEYS,
  envEntry,
  goesTo,
  isOverridable,
  isStackProduced,
} from "../config/env-registry.mjs";
import { formatEnvValue, parseDotenv } from "./dotenv.mjs";

const [target, outputPath] = process.argv.slice(2);

if (!target || !outputPath || !["local", "vercel", "github"].includes(target)) {
  console.error(
    "Usage: node scripts/distribute-env.mjs <local|vercel|github> <output-file> < dotenv-document",
  );
  process.exit(2);
}

// Resolved against the working directory, not this file: the deploy runs from
// the repo root, and a test runs from a temporary one.
const MANUAL_PATH = join(process.cwd(), ".env.manual");

const parse = parseDotenv;

const stackValues = parse(readFileSync(0, "utf8"));
const seed = stackValues.APP_SECRET_SEED;
if (!seed) {
  console.error(
    "The dotenv document has no APP_SECRET_SEED. Deploy the current CDK stack before distributing it.",
  );
  process.exit(1);
}

const manualValues = existsSync(MANUAL_PATH) ? parse(readFileSync(MANUAL_PATH, "utf8")) : {};

// The rule that replaces the merge. `.env.manual` may only speak for values a
// human is the source of; a stack-produced key in it would be a second opinion
// about a credential, which is exactly what this design removes. Refused rather
// than ignored, because a value someone took the trouble to type should never be
// silently discarded — that silence is what hid the original bug for a week.
const trespassing = Object.keys(manualValues).filter(
  (key) => manualValues[key] && isStackProduced(key),
);
if (trespassing.length > 0) {
  console.error(
    `.env.manual sets ${trespassing.join(", ")}, which the deployed stack produces. There is no local override for a minted credential: delete those lines. If the deployed value is wrong, fix it in the stack and redeploy.`,
  );
  process.exit(1);
}

const derivedValue = (purpose) =>
  Buffer.from(hkdfSync("sha256", Buffer.from(seed), "diveday-app-secret-v1", purpose, 32)).toString(
    "base64",
  );

const values = {
  ...stackValues,
  // Manual values, and an override of a checked-in constant where someone has
  // written one. Filtered rather than spread whole so a key this app does not
  // read cannot arrive through the back door.
  ...Object.fromEntries(
    Object.entries(manualValues).filter(([key, value]) => value && isOverridable(key)),
  ),
  AUTH_SECRET: derivedValue("auth"),
  SECRET_ENCRYPTION_KEY: derivedValue("credential-sealing"),
  CRON_SECRET: derivedValue("cron"),
};

const header = {
  local: [
    "# Generated by pnpm infra:deploy from the deployed stack plus .env.manual.",
    "# Overwritten on every deploy — edit .env.manual instead.",
  ],
  vercel: ["# Generated for Vercel Production from diveday/env plus .env.manual; do not edit."],
  github: ["# Generated for GitHub Actions from diveday/env; do not edit."],
}[target];

const lines = ENV_KEYS.filter((key) => goesTo(key, target))
  // A key the stack has no value for is written blank rather than omitted, so
  // the file always shows the whole shape and `pnpm check:env` can say what is
  // unset. For Vercel and GitHub an empty value is dropped instead: pushing one
  // would overwrite a variable set by hand in a console with nothing.
  .map((key) => [key, values[key] ?? envEntry(key)?.value ?? ""])
  .filter(([, value]) => target === "local" || value !== "")
  .map(([key, value]) => `${key}=${formatEnvValue(value)}`);

writeFileSync(outputPath, [...header, "", ...lines, ""].join("\n"));
